name: export-solution-on-main
# Export solution from DEV environment. Unpack it and prepare, commit and push
# a git branch with the changes.

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'Name of the solution to worked on from Power Platform.'
        required: true
        default: FinanceTrackerTransactionInput
      commit_message:
        description: 'Commit message to use when commiting the solution. " must be escaped (\")'
        required: true
        default: 'Export - DEV Environment'
permissions:
  contents: write
jobs:
  export-solution-on-main:
    runs-on: ubuntu-latest
    # or you can say runs-on: windows-latest
    steps:
    - uses: m-metz/actions/export-solution-on-main@main
      with:
        solution_name: ${{ github.event.inputs.solution_name }}
        commit_message: ${{ github.event.inputs.commit_message }}
